#  Este es un archivo de rubocop simple donde se deshabilitan
# muchas de las reglas que suele checkear rubocop, para dejar
# una base simple y se tengan que preocupar solo de ciertos "cops"

#  Al final de este archivo, si encuentras que te ayudaría a tener
# un código mas ordenado, puedes añadir todos los cops que creas convenientes.

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "test/fixtures/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "app/views/**/*"
    - "config/environments/*"
    - "node_modules/**/*"

# Layout
Layout/LineLength:
  Max: 120
  Enabled: true
Layout/AssignmentIndentation:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/IndentationStyle:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
  Width: 2
Layout/MultilineMethodCallIndentation:
  Enabled: true
Layout/ArgumentAlignment:
  Enabled: true
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Layout/ArrayAlignment:
  Enabled: true

# Naming
Naming/ConstantName:
  Enabled: true
Naming/FileName:
  Enabled: true
Naming/MethodName:
  Enabled: true
Naming/AsciiIdentifiers:
  Enabled: true
Naming/BlockParameterName:
  Enabled: true
  MinNameLength: 2
Naming/VariableName:
  Enabled: true

# Style
Style/Next:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantParentheses:
  Enabled: true
Style/ReturnNil:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/DoubleNegation:
  Enabled: true
Style/EmptyElse:
  Enabled: true

# Lint
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperator:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/RedundantWithIndex:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
Lint/EmptyExpression:
  Enabled: true
Lint/ShadowedArgument:
  Enabled: true



# Añade aquí todos los Cops que quieras: # ----- AGREGADO POR DIEGO -------
# REVISAR: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/
Style/Documentation:
  Enabled: false
Style/AndOr: # Prefer &&/|| over and/or.
  Enabled: false
# Prefer Foo.method over Foo::method
Style/ColonMethodCall:
  Enabled: true
# Use my_method(my_arg) not my_method( my_arg ) or my_method my_arg.
Lint/RequireParentheses:
  Enabled: true
Layout/CaseIndentation: # Align `when` with `case`.
  Enabled: false
Layout/CommentIndentation: # Alinee comentarios con definiciones de métodos.
  Enabled: true
Layout/ElseAlignment: # agregado
  Enabled: true
# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true
# Espacio despues de cada comentario
Layout/LeadingCommentSpace:
  Enabled: true
Layout/SpaceAfterColon:
  Enabled: true
# Espacio despues de una, coma
Layout/SpaceAfterComma:
  AutoCorrect: true
  Enabled: true
Layout/SpaceAfterSemicolon:
  Enabled: true
Layout/SpaceAroundKeyword:
  Enabled: true
# Alinia repetidos
Layout/ClosingHeredocIndentation:
  Enabled: false
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false

Metrics/BlockLength:
  Max: 150
  Enabled: true

Metrics/MethodLength:
  Max: 50
  Enabled: true

Metrics/AbcSize:
  Max: 50
  Enabled: true

Metrics/PerceivedComplexity:
  Max: 12
  Enabled: true
